### ISSUE TITLE
✅User Story 1: Display the first puzzle 🧩

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#1]
## Value proposition

As a player
I want to see the first puzzle
So that I can gain a first impression 

## Description

![Image](https://user-images.githubusercontent.com/124199994/229275854-1a385a00-52a2-4bf9-ad3c-0c38c3734bb9.png)

## Acceptance criteria

- [x] Create a paragraph with the clue: "Gib den Code ein!"  🧩
- [x] The predefined color code is displayed  🧩
- [x] An area with 3 fields is displayed  🧩
  - [x] in each field you can choose between 8 colors: yellow, green, blue, brown, red, gray, orange, purple
  - [x] symbols are placed above the color field 

## Tasks

- [x] Create a new branch
- [x] Create a paragraph with the clue: "Gib den Code ein!"
- [x] Render the predefined  color code
- [x] Create a formfield
  - [ ] #8
  - [x] Label with symbols  
- [x] All acceptance criteria marked with  🧩 are covered by component testing

## Complexity

M
