### ISSUE TITLE
User Story 6: Display collected  puzzle pieces in an area 🧩

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#13]
## Value proposition

As an escape room player
I want to  be able to see the puzzle pieces in a specific area
So that I have an overview of the progress collected pieces.

## Description

![Image](https://user-images.githubusercontent.com/124199994/231142560-f1e4823c-1fe9-44af-8ca2-3ba614ed3a32.png)

## Acceptance criteria

- [x]  A separate section is displayed, which 🧩
  - [x] contains a heading with the following text  "Eingesammelte Puzzleteile". 🧩
  - [x] contains a puzzle piece and next to it a counter 🧩
- [x] Clicking on the puzzle pieces in the room, the counter in the collection area is incremented 

## Tasks

- [x] Create a new branch
- [x] Create a collection area
- [x] Create a header with the text: "Collected puzzle pieces".
- [x] Create a feature that increments the counter when you click on the puzzle pieces.
- [x] Create a paragraph with a puzzle piece and the counter
- [x] All acceptance criteria marked with 🧩 are covered by component testing

 
## Complexity

S

**Comment by toshydev** [comment]
LGTM! ✅
