### ISSUE TITLE
User Story 7: If all puzzle pieces are collected a clue appears

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#14]
## Value proposition

As an escape room player
I want to receive a further clue
So that the whole puzzle becomes more complex.

## Description

![Image](https://user-images.githubusercontent.com/124199994/231179167-c3f929ea-2c8b-4e4d-961c-5c904733fa13.png)

## Acceptance criteria

- [x] If all puzzle pieces are collected a clue appears
- [x] hidden color code is customized

## Tasks

- [x] Create a new branch
- [x] Delete the right symbol from the hidden color code
- [x] When 9 puzzle pieces are collected
  - [x] hide the collecting area
  - [x] show a clue 

## Complexity

M

**Comment by AnjaSiewert** [comment]
Hi Ella,
- first tasks and acceptance criteria are exactly the same so you can delete the first tasks
- in second task I guess you forgot to finish the sentence? :)
PS: I love your app 🚀
