### ISSUE TITLE
User Story 8: Create a  crossword puzzle

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#15]
## Value proposition

As an escape room player
I want to select a new puzzle in the room
So that I can solve the crossword puzzle.

## Description

![Image](https://user-images.githubusercontent.com/124199994/231195646-c2fdbb7d-3523-407c-bbe8-0287c59072e2.png)

## Acceptance criteria

- [x] A link with the symbol "📝" is displayed 🧩
- [x] Clicking the link redirect to the crossword page 
- [x] On the crossword page a crossword puzzle is displayed, with
  - [x] an area where the solution will be shown later
  - [x] an area with hints to the crossword puzzle. 🧩
  - [x] a back-button  

## Tasks

- [x] Create the page `page/crossword`
  - [x] Create a back-button
  - [x] Create a table where the solution will be shown later
  - [x] Create a list with hints to the crossword
- [x] Create a link to the crossword page
- [x] All acceptance criteria marked with 🧩 are covered by component testing

## Complexity

L

**Comment by DominicWebDev** [comment]
lgtm exicted to try your app in the future
