### ISSUE TITLE
User Story 9: I can enter my answer

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#16]
## Value proposition

As an escape room player
I want to see a form field 
So that I can enter my answer.

## Description

![Image](https://user-images.githubusercontent.com/124199994/231239104-4932e93f-84a3-4d9d-abd6-746e1bdf3169.png)

## Acceptance criteria

- [x] A form field is displayed 🧩 
- [x] The current hint is displayed above the form field  
   - [x] If no hint is selected, "Wähle eine Frage aus!" is displayed above the form field  
- [x] If the answer was correct, it will be displayed in the crossword field

## Tasks

- [x] Create a form field 
- [x] check that the answer is correct
- [x] Show the correct answer in the crossword field
- [x] All acceptance criteria marked with 🧩 are covered by component testing

 
## Complexity

L

**Comment by FrankSiyli** [comment]
Nice idea😀
