### ISSUE TITLE
User Story 10: I will be notified if my answer is right or wrong

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#17]
## Value proposition

As an escape room player
I want to be notified if my answer is right or wrong
So that  I can correct my answer if necessary

## Description

![Image](https://user-images.githubusercontent.com/124199994/231405686-d428030a-52b3-4643-a44a-3502ea1d8b9d.png)

## Acceptance criteria

- [x] Number of letters from the current word is displayed 
- [x] Number of letters entered is displayed  
- [x] A submit button is displayed
  - [x] Clicking the button the form field will be cleared
- [x] The toast massage appears:" ❌ Falsch"appears if the answer is wrong 🧩
- [x] The toast massage: "✅ Richtig" appears if the answer is correct 🧩

## Tasks

- [x] Create a line that shows how many letters the selected word has and how many letters have already been entered.
- [x] Create a submit button 
- [x] Create a toast massage with the text: " ❌ Falsch"
- [x] Create a toast massage with the text: "✅ Richtig"
- [x] All acceptance criteria marked with 🧩 are covered by component testing

## Complexity

L

**Comment by FrankSiyli** [comment]
Nice idea. Do you check the answer onChange or is the submit button another US?
