### ISSUE TITLE
User Story 11: A clue appears when the crossword is solved

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#18]
## Value proposition

As an escape room player
I want to  be able to to solve the crossword puzzle
So that  I get another clue

## Description

![Image](https://user-images.githubusercontent.com/124199994/231409143-85a45ff9-cfca-40e3-b86a-1c33810b997d.png)

## Acceptance criteria

- [x] If the crossword puzzle is solved, a clue appears
- [x] hidden color code is customized

## Tasks

- [x] Create a new branch 
- [x] Delete the right symbol from the hidden color code
- [x] When the crossword is solved
   - [x] hide the crossword puzzle
   - [x] show a clue

 
## Complexity

S

**Comment by augustinanders** [comment]
LGTM! 🚀
