### ISSUE TITLE
User Story 13: Create homepage

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#26]

**Comment by ella-blaupause** [comment]
## Create homepage

## Value proposition

As an escape room player
I want to  get to the homepage when i select the website
So that  I can navigate to the game.

## Description






![Image](https://user-images.githubusercontent.com/124199994/232774890-209c947b-7363-46f3-ab48-dd3995d9e7ab.png)





## Acceptance criteria

- [ ] Start button ist displayed
- [ ] home-svg is filled

## Tasks

- [ ] create a button with the text "Start"



 
## Complexity

XS

**Comment by dennisbuchwald** [comment]
LGTM!
