### ISSUE TITLE
User Story 14: Create a picture of a room

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#27]
## Value proposition

As an escape room player
I want to see a picture of a room
So that I have the feeling of being in a real room.

## Description

Graphical representation of a room with clickable elements.

## Acceptance criteria

- [ ] You see a picture of a room

## Tasks

- [ ] Create a room in RoomSketcher (or similar)
- [ ] Draw the room in figma

## Complexity

XL

**Comment by rabe200** [comment]
Lgtm
