### ISSUE TITLE
User Story 15: I can ask ChatGPT for a hint

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#28]
## Value proposition

As an Escape Room player
I want to  be able  to ask ChatGPT 
So that I can continue the puzzle

## Description

![Image](https://user-images.githubusercontent.com/124199994/232799371-b3ed2743-4234-42d6-9260-b5c0c888261e.png)

## Acceptance criteria

- [x] The text "Du brauchst Hilfe beim Rätsel? 
Vielleicht bringt dich ChatGPT weiter! " is displayed 🧩 
- [x] An input field is displayed 
- [x] I can enter my question in an input field🧩 
- [x] A possible answer from ChatGPT is displayed

## Tasks

- [x] Create a new branch 
- [x] Create a form element
   - [x]  Create a label element with the text ""Du brauchst Hilfe beim Rätsel? 
Vielleicht bringt dich ChatGPT weiter!"
   - [x] Create a input element with the placeholder text "Frage eingeben"
   - [x] In one area the answer from ChatGPT is displayed
- [x]  Create a folder `api`
  - [x] Create a file `api/generate.js`
- [x] Create a file `.env` with OpenAI API key
- [x] All acceptance criteria marked with 🧩 are covered by component testing

 
## Complexity

L

**Comment by rabe200** [comment]
lgtm !
