### ISSUE TITLE
User Story 16: I would like a larger crossword puzzle

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#29]
## Value proposition

As an Escape Room player
I would like a larger crossword puzzle
so that the game becomes more interesting

## Description

![Image](https://user-images.githubusercontent.com/124199994/232822956-29ad8842-6a0e-46d8-96aa-ee419d363063.png)

## Acceptance criteria

- [x] At least 7 questions are displayed in the list
- [x] The solution field is adapted to the questions

## Tasks

- [x] Create a new branch
- [x] Create 7 new questions
- [x] Customize the  solution field 

## Complexity

S
