### ISSUE TITLE
User Story 3: Create room

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#3]
## Value proposition

As an exit room player
I want to be in a room
So that I can pass the first challenge.

## Description

![Image](https://user-images.githubusercontent.com/124199994/230111797-8e14053c-cbf8-4392-984b-258390393e93.png)

## Acceptance criteria

- [x] A door button is displayed
- [x] Clicking the door button takes me to the color code puzzle
- [x] On the page with the color code is a back button displayed 
- [x] Clicking the back button takes me back to the room page

## Tasks

- [x] Create a new branch
- [x] ~~Create a page `pages/room.js`~~
   - rename `pages/index.js -> pages/door.js` and `pages/room.js -> pages/index.js`
- [x] Render a door button on the room page
- [x] Render a back button on the puzzle page

## Complexity

S

**Comment by PacoSchwab** [comment]
LGTM, but a suggestion: in the color code room the "back" button is also a "door button"? If so, maybe you could state that in your acceptance criteria as well. :)

**Comment by ella-blaupause** [comment]
thanks for the review✌️
I don't understand your suggestion? 
The back button is not the same as the door button. The two buttons are on two different pages.
I have replaced the image in the description, perhaps it will be clear

**Comment by ella-blaupause** [comment]
Thanks Paco👍
