### ISSUE TITLE
User Story 17: The selected hint is marked

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#30]
## Value proposition

As an Escape Room player
I want to be get displayed which question is currently selected
So that the crossword puzzle becomes even more accessible

## Description

![Image](https://user-images.githubusercontent.com/124199994/232830923-363e3d01-1961-44d6-ac9e-db44c86a20ac.png)

## Acceptance criteria

- [x] The selected hint is marked in the list
- [x] The selected hint is marked in the solution field

## Tasks

- [x] Create a red rectangle for the selected hint in the list
- [x]  Create a red rectangle for the selected hint in the list

## Complexity

M

**Comment by Satttoshi** [comment]
Wow, what a cool addon! Instead of using the term 'user-friendly,' which can be limiting, 'accessible' is a better choice.

LGTM :rocket:
