### ISSUE TITLE
User Story 18: Create a profile

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#31]
## Value proposition

As an escape room player
I would like to create a profile,
so that I will be informed about my score

## Description

![Image](https://user-images.githubusercontent.com/124199994/233189165-0eb467db-f4f0-4228-a9ec-69cef83f2c08.png)

## Acceptance criteria

- [x] I can add my name  🧩 
- [x] I can choose between two profile pictures
- [x] The number of puzzles solved is displayed  🧩 

## Tasks

- [x] Create a new branch
- [x] Create two profile pictures
- [x] Create a line with the score
- [x] All acceptance criteria marked with 🧩 are covered by component testing

## Complexity

M

**Comment by PacoSchwab** [comment]
LGTM, maybe you could add the darkmode feature to your value proposition as well?

**Comment by ella-blaupause** [comment]
You are right. Maybe it's better to create the button with the next user story together with the dark mode feature
