### ISSUE TITLE
User Story 4:

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#4]

**Comment by ella-blaupause** [comment]
## When the light is turned off a clue appears in the room 💡

## Value proposition

As a escape room player
I want to turn off the light
So that I can discover the color code clue.

## Description

![Image](https://user-images.githubusercontent.com/124199994/229376044-ba6b305e-5857-4004-ade9-7914bcf5fc95.png)


## Acceptance criteria

- [ ] Color code clue is deleted in the color code component
- [ ] on/off-button in the room ist displayed 🧩
- [ ] 


## Tasks

- [ ] 
- [ ] All acceptance criteria marked with  🧩 are covered by component testing

## Complexity

L
