### ISSUE TITLE
User Story 19: Create zustand store

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#40]
## Value proposition

As a developer
I want more order for my states
So that I have a better overview.

## Description

The state store in React is used to manage data centrally in the application and simplify data flow between different components. This reduces the complexity of the application and increases maintainability, especially when the application has a large amount of data and/or complex interactions.

## Acceptance criteria

- [ ] Prop drilling removed
- [ ] App works without bugs

## Tasks

- [ ] Create a new branch
- [ ] Create a zustand folder
- [ ] Refactor Code

## Complexity

L
