### ISSUE TITLE
User Story 20: User login

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#41]
## Value proposition

As a player
I want to be able to log in 
so that my personal game progress is saved

## Acceptance criteria

- [ ] Log in with GitHub

## Tasks

- [ ] Create a new branch
- [ ]  Implement db
- [ ]  Implement next/auth

## Complexity

L
