### ISSUE TITLE
User Story 21: Dark mode

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#42]
## Value proposition

As an escape room player
I want to be able to choose between dark and light mode
So that  I have more control over my user experience.

## Description

![Image](https://user-images.githubusercontent.com/124199994/234954352-9108d86c-33a3-4558-8673-bf0c7584ad21.png)

## Acceptance criteria

- [ ] A select element is displayed  🧩 
- [ ] You can choose between default setting from pc, dark and light mode
- [ ] Dark mode is visible when switched on

## Tasks

- [ ] Create a new branch
- [ ] Add an select element
- [ ] Implement a dark theme
- [ ] All acceptance criteria marked with 🧩 are covered by component testing

## Complexity

M

**Comment by AnjaSiewert** [comment]
Hi Ella, I am a bit confused with the second Acceptance criteria, what is the default mode? Is there a third option next to light and dark mode? 
If not I would write something like: User can choose between light and dark mode whereas light mode is set by default, otherwise this might me a bit misleading

**Comment by ella-blaupause** [comment]
Hi 🦦,
I have oriented myself here to MDN (see picture).
The default modes describes the default choice of your PC



![Image](https://user-images.githubusercontent.com/124199994/234968953-79aa6df2-736f-4f39-80c9-03939911c668.png)


Is that clearer with the 3 modes?

**Comment by ella-blaupause** [comment]
The picture has become large 😲

**Comment by AnjaSiewert** [comment]
perfectly clear now! thanks for your explanation :) Best regards, the 🦦
