### ISSUE TITLE
Saving my score when logging in

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#47]
## Value proposition

As an Escape Room player
I would like to have my game state saved in the backend
So that I can continue playing the game from any device

## Description

The current game state is saved in the backend, e.g. the collected puzzle pieces or the solved crossword clues.

## Acceptance criteria

- [ ] Number of solved puzzles is saved
- [ ] collected puzzle pieces are saved
- [ ] solved clues in the crossword puzzle are saved 
- [ ] selected avatar is saved

## Tasks

- [ ] state for the solved puzzles is stored in the backend
- [ ] save puzzle pieces in backend
- [ ] state for the solved crossword clues are stored in the backend

## Complexity

M
