### ISSUE TITLE
Responsive website

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#48]
## Value proposition

As an Escape Room player
I would have a responsive website
so that the game is well playable on any screen

## Description

The game adapts to the width of the screen. On the "Room" page, the image is stored fixed in the center, for large screens. On small screens you can scroll the image. Puzzle pieces have a fixed place on all screens.

## Acceptance criteria

- [ ] clickable divs and puzzle pieces are placed above the corresponding image. On all screens
- [ ] puzzle pieces are filled in on all browsers
- [ ] Header and footer is adapted to the size of the screen

## Tasks

- [ ] instead of grid the puzzle pieces are placed with positon: absolute;
- [ ] fix the fill property of the puzzle pieces
- [ ] Width of header and footer are set with mediaqueries

## Complexity

M
