### ISSUE TITLE
User Story 4: When the light is turned off a clue appears in the room 💡

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#5]
## Value proposition

As an escape room player
I want to turn off the light
So that I can discover the color code clue.

## Description

![Image](https://user-images.githubusercontent.com/124199994/229376595-6e6472a3-04a7-4112-9436-924a361437f6.png)

## Acceptance criteria

- [x] Color code clue is deleted in the color code component
- [x] on/off-button in the room ist displayed 
- [x] When the light is turned off the clue appears 

## Tasks

- [x] Create a new branch
- [x] Cut out the clue and paste it into the room
- [x] Hide the clue when the light is on and appears  the clue  when the light is off
- [x] Lifting necessary state up

## Complexity

M

**Comment by FrankSiyli** [comment]
Nice idea.

**Comment by ella-blaupause** [comment]
Thanks
