### ISSUE TITLE
User Story 5: Collect puzzle pieces 🧩🧩🧩

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#6]
## Value proposition

As an escape room player
I want to see puzzle pieces in the room
So that I can collect them.

## Description

![Image](https://user-images.githubusercontent.com/124199994/229471273-c5dc4a36-5a49-48ed-bb3d-081f7f63a976.png)

## Acceptance criteria

- [x] 9 puzzle pieces are displayed 🧩 
- [x] The puzzle pieces are distributed in the room
- [x] Clicking on puzzle pieces it disappears 

## Tasks

- [x] Create a new branch
- [x] Use CSS grid to place pieces
- [x] Hide puzzle piece by clicking 
- [x] All acceptance criteria marked with  🧩 are covered by component testing

## Complexity

M

**Comment by ella-blaupause** [comment]
## Collect puzzle pieces 🧩🧩🧩

## Value proposition

As a escape room player
I want to see puzzle pieces in the room
So that I can collect them.

## Description




## Acceptance criteria

- [ ] 


## Tasks

- [ ]
- [ ] All acceptance criteria marked with  🧩 are covered by component testing

## Complexity

XL

**Comment by toshydev** [comment]
LGTM 👌
